### ISSUE TITLE
Release Plan Checklist

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/ads-for-wp#19]
- [ ] Enable / Disable should apear inline 

- [ ] debug errors

- [ ] Code cleaning, Pre-fixing and  text domains.

- [ ] Code Testing (Automated and manual) 

- [ ] Release on WP.org
