### ISSUE TITLE
AD Analytics Roadmap

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/ads-for-wp#77]
- [x] Pie chart of (Mobile VS Desktop, AMP vs Non-AMP & data which says "Out of 57% of your mobile visitors, 37% of them came from AMP)

- [ ] Ad specific Report

- [ ] Post specific Report

- [ ] Impressions and clicks with link to View full report

- [ ] Top 10 Posts / Pages by Traffic / Revenue

- [ ] Top 10 AMP Pages by traffic and rev
